.TH tar-xz-slicer 1 "30 June 2025" "version 0.1" "Archiving CLI tool"
.SH NAME
tar-xz-slicer \- CLI-утилита для упаковки директорий с .tar.xz и делением на части без временных файлов
.SH SYNOPSIS
.B tar-xz-slicer
.RI [ command ] " [options]"
.SH DESCRIPTION
Упаковывает каталоги в потоковый tar.xz-архив с последующей нарезкой по размеру (по умолчанию 1ГБ),
а также может объединять части и распаковывать архив.

.SH COMMANDS
.TP
.B pack
<каталог> [размер_слайса] [префикс]
Создаёт .tar.xz архив из каталога и разбивает на части указанного размера.

.TP
.B unpack
<префикс>
Объединяет слайсы и распаковывает содержимое архива.

.TP
.B \-\-help
Выводит справку по использованию.

.TP
.B \-\-list
Показывает доступные команды.

.SH EXAMPLES
.TP
.B tar-xz-slicer pack ./project 1g backup_
Создаёт архив `backup_aa`, `backup_ab`... из `./project`.

.TP
.B tar-xz-slicer unpack backup_
Распаковывает `backup_*` обратно в текущую директорию.

.SH AUTHOR
Mykola Matvyeyev + Copilot 🛠

.SH LICENSE
MIT
